name: WakaTime ReadMe

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          # GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # REPOSITORY: <emravoan/emravoan>